
databases:
  - name: mysite
  databaseName: mysite user: mysite plan: free
  services:
  type: web
  name: mysite

  services:
  - type: web
  name: mysite
  runtime: ruby
  plan: free
  buildCommand: "./bin/render-build.sh"
  # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
  startCommand: "bundle exec rails server"
  envVars:
      - key: DATABASE_URL
        fromDatabase:
        name: mysite
        property: connectionString
    - key: RAILS MASTER_KEY
    sync: false- key: WEB CONCURRENCY
    value: 2 # sensible default