default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: plant_capstone_app_development

test:
  <<: *default
  database: your_test_db_name

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
