default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: your_local_dev_db_name

test:
  <<: *default
  database: your_test_db_name

production:
  <<: *default
  # DATABASE_URL will be used in production
