# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end


User.create(name: "Nathaniel", email: "nathaniel@email.com", password_digest: "password", image_url: "https://scontent-iad3-1.xx.fbcdn.net/v/t39.30808-6/427971800_1102841000846756_6910868494923997282_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=ibHF3yXDygsQ7kNvwHeRoLE&_nc_oc=AdkZAW0GEH3CD00nOrpNN4_M9DKJisE9i8BK9pDzU9PeCx36Mou2N7Lb_4dDXoJnu5yzqO0GLu5VH_coSoyqeiIJ&_nc_zt=23&_nc_ht=scontent-iad3-1.xx&_nc_gid=r6KeWxMTPuLsCvY62CD6Pw&oh=00_AYHKtVAhDthVNFEhaZOf3sDXMhKxkO7-BoJK1BTrxGBgpA&oe=67F4D53C")

Plant.create(name: "palm tree", description: "A palm tree is a tropical plant known for its tall, slender trunk and crown of large, fan-like or feathery fronds. Found in warm climates, palms thrive in sandy soils and are often seen along beaches, deserts, and urban landscapes. Some species, like the coconut palm, produce edible fruits, while others are valued for their ornamental beauty. Palms symbolize relaxation and exotic destinations, commonly associated with tropical islands and vacation spots. They are resilient, with deep roots that help them withstand strong winds and harsh conditions.", amount_of_sun: 100, days_to_water: 7)
Plant.create(name: "Rhubarb", description: "Rhubarb is a hardy perennial plant known for its thick, tart, red or green stalks, which are commonly used in cooking and baking. While its stalks are edible, the leaves contain toxic levels of oxalic acid and should not be consumed. Rhubarb thrives in cool climates and well-drained soil, often harvested in spring and early summer. It is popularly used in pies, jams, and sauces, often paired with sweeteners to balance its natural tartness. The plant’s large, broad leaves and thick stems make it an attractive addition to gardens.", amount_of_sun: 30, days_to_water: 3)
Plant.create(name: "Cabbage", description: "Cabbage (Brassica oleracea) is a leafy biennial plant grown as an annual, known for its dense, compact head of smooth or crinkled leaves. It thrives in cool climates and well-drained, nutrient-rich soil. Cabbage plants have a shallow root system and require consistent moisture to develop firm, healthy heads. The outer leaves spread wide, protecting the inner layers as the plant matures. Available in green, red, and savoy varieties, cabbage is resistant to frost and can tolerate colder temperatures better than many other leafy plants. It belongs to the Brassicaceae family, related to broccoli, cauliflower, and kale. Cabbage is susceptible to pests like cabbage worms and aphids, requiring careful cultivation and pest management. When left to flower, cabbage produces tall stalks with yellow blossoms that eventually seed. Its strong adaptability and high yield make it a staple in many gardens and agricultural systems worldwide.", amount_of_sun: 35, days_to_water: 3)
